# Generated by Django 4.0.5 on 2022-06-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cold_start',
            field=models.BooleanField(default=False, verbose_name='cold_start'),
        ),
    ]
