# Generated by Django 4.0.5 on 2022-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_cold_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_based',
            field=models.IntegerField(default=5),
        ),
    ]
